### PR TITLE
Fix pattern to create master page

### LINKED ISSUE #11: Apply the new pattern to create MasterPage
A new pattern to create MasterPage was discussed in https://github.com/Starcounter/Guidelines/issues/23 and implemented for reference in https://github.com/StarcounterApps/Website/pull/106.

Please apply the same pattern in Launchpad app, namely:

- rename the class `StandalonePage` to `MasterPage` (json, json.cs, html files)
- replace `Handle.GET("/launchpad/standalone"` handler with a `GetSessionFromMaster` method

### PR DESCRIPTION
**Pull request by bouguila**
Fix #11
replaced StandalonePage -> MasterPage
replaced Handler.GET("/launchpad/standalone"..  -> getMasterpageFromSession method

### CODE REVIEW

File: src/Launchpad/Api/MainHandlers.cs [hunk 1]
```diff
@@ -60,5 +43,22 @@ public void Register()
 
             Blender.MapUri("/launchpad/partial/launchpad", "launchpad"); // launchpad panel; used in Launcher/Website
         }
+        protected MasterPage GetMasterPageFromSession()
```
Comment (PatrykSzwer) [inline src/Launchpad/Api/MainHandlers.cs]: Missing blank space before method header.
